In [1]:
import numpy as np

# Numpy
* array - n-dimensional
* matrices or matrix - rows and comumns

In [2]:
l1 = [2, 4, 6, 7, 10, 12]
l2 = [1, 3, 5, 7, 9, 11]
print(l1)

[2, 4, 6, 7, 10, 12]


In [3]:
a1 = np.array(l1)
print(a1)

[ 2  4  6  7 10 12]


In [4]:
a2 = np.array(l2)
print(a2)

[ 1  3  5  7  9 11]


In [5]:
 np.array([23, 43, 54, 23], dtype="int")

array([23, 43, 54, 23])

In [6]:
 np.array([23, 43, 54, 23], dtype="float")

array([23., 43., 54., 23.])

In [7]:
  np.array([23, 43, 54, 23], dtype="str")

array(['23', '43', '54', '23'], dtype='<U2')

In [8]:
 np.array([23, 43, 54, 23, "str", 76], dtype="int")

ValueError: invalid literal for int() with base 10: 'str'

# Numpy attributes
* shape
* size
* dtype
* ndim

In [9]:
# shape shows rows, coloumn
a1.shape

(6,)

In [10]:
# it means rows * coloumn
a1.size

6

In [11]:
# it shows the type of array
a1.dtype

dtype('int64')

In [12]:
b1 =   np.array([23, 43, 54, 23], dtype="str")
b1.dtype

dtype('<U2')

In [13]:
# ndim means numbers of dimensions
a1.ndim

1

In [14]:
l1

[2, 4, 6, 7, 10, 12]

In [15]:
l1 * 2

[2, 4, 6, 7, 10, 12, 2, 4, 6, 7, 10, 12]

In [16]:
a1 * 2

array([ 4,  8, 12, 14, 20, 24])

In [17]:
a1 + a2

array([ 3,  7, 11, 14, 19, 23])

In [18]:
a1 > 4 

array([False, False,  True,  True,  True,  True])

In [19]:
a1[a1 > 4]

array([ 6,  7, 10, 12])

# Matrces or Matrix

In [20]:
# how to create matrix in from array
a3 = np.array([[1,2,3],[4,5,6]])

In [21]:
a4 = np.array([[10,20,30,40],[23,45,65,89],[45,65,4,64]])

In [22]:
a3.shape

(2, 3)

In [23]:
a4.shape

(3, 4)

In [24]:
a3.size

6

In [25]:
a4.size


12

In [26]:
a3.ndim

2

In [27]:
a4.ndim

2

In [28]:
a3.dtype

dtype('int64')

In [29]:
a4.dtype

dtype('int64')

# Random array

In [30]:
np.random.random(size=5)

array([0.49223526, 0.65424162, 0.57846181, 0.79581625, 0.37364186])

In [31]:
np.random.rand(5)

array([0.61415482, 0.54339312, 0.65504021, 0.87219419, 0.46762594])

In [32]:
np.random.randn(5)

array([-0.44846871, -1.3434018 ,  0.38152994, -1.32696544, -0.29344366])

In [34]:
rng = np.arange(15)

In [35]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
lspace = np.linspace(1, 4, 8)

In [39]:
lspace

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        ])

In [42]:
emp = np.empty((4, 6))

In [43]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.11260280e-306, 1.89146896e-307, 7.56571288e-307],
       [4.00544531e-307, 1.11261095e-306, 3.56043054e-307,
        1.37961641e-306, 2.22518251e-306, 1.33511969e-306],
       [6.23037996e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 1.86921143e-306, 6.23061763e-307],
       [6.23053954e-307, 1.60220800e-306, 7.56601165e-307,
        1.29061414e-306, 1.42410974e-306, 1.42410974e-306]])

In [44]:
emp_like = np.empty_like(lspace)

In [45]:
emp_like

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        ])

In [49]:
ide = np.identity(5)

In [50]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
ide.shape

(5, 5)

In [72]:
arr = np.arange(99)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [79]:
arr.shape

(99,)

In [76]:
# 3*33 = 99 
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [80]:
# this is used to restore the array shape 
arr = arr.ravel()

In [81]:
arr.shape

(99,)

# *attributes in mumpy* 

In [82]:
X = [[1,2,3], [4,5,6], [7,1,0]]

In [83]:
ar = np.array(X)

In [87]:
ar.sum(axis = 0)

array([12,  8,  9])

In [89]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [90]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [91]:
ar.flat

In [93]:
for item in ar.flat:
    print(item)
    


1
2
3
4
5
6
7
1
0


In [94]:
ar.ndim

2

In [95]:
ar.size

9

In [96]:
# nbytes =  total bytes consumed how much space they are occupying 
ar.nbytes

72

In [98]:
one = np.array([1,2,3,454,2])

In [99]:
one.argmax()

np.int64(3)

In [101]:
one.argsort()

array([0, 1, 4, 2, 3])

In [103]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [104]:
ar.argmin()

np.int64(8)

In [105]:
ar.argmax()

np.int64(6)

In [109]:
ar.argmax(axis=0)

array([2, 1, 1])

In [108]:
ar.argmax(axis=1)

array([2, 2, 0])

# For taking squareRoot of a array

In [111]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [112]:
ar.sum()

np.int64(29)

In [113]:
ar.max()

np.int64(7)

In [114]:
ar.min()

np.int64(0)

In [116]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [117]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [118]:
np.count_nonzero(ar)

8

In [119]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [120]:
import sys

In [123]:
py_ar = [0,4,55,2]

In [124]:
np_ar = np.array(py_ar)

In [125]:
sys.getsizeof(1) * len(py_ar)

112

In [126]:
np_ar.itemsize * np_ar.size

32

In [129]:
py_ar.sort

<function list.sort(*, key=None, reverse=False)>